#baseURL = "eristocrates.dev"
copyright = "made with hugo by eristocrates"
enablerobotstxt = true
languagecode = "en-US"
paginate = 50
timezone = "America/New_York"
titlecasestyle = "Go"


[languages.en]
title = "the eristocracy"
weight = 10

[[languages.en.menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[languages.en.menu.main]]
identifier = "bof"
name = "BOF"
url = "/bof/"
weight = 20

[[languages.en.menu.main]]
identifier = "boftt"
name = "BOF:TT"
parent = "bof"
url = "/bof/event146"
weight = 10

[[languages.en.menu.main]]
identifier = "keeb"
name = "Keyboards"
url = "/keeb/"
weight = 30

[[languages.en.menu.main]]
identifier = "keyzen"
name = "keyzen"
parent = "keeb"
url = "/keeb/keyzen"
weight = 10

[markup.goldmark.renderer]
unsafe = true

[markup.tableofcontents]
endlevel = 6
ordered = true
startlevel = 2

[[module.imports]]
path = "github.com/willfaught/paige"

[outputs]
home = ["html", "paige-search"]
section = ["html"]
taxonomy = ["html"]
term = ["html"]

[params.paige]
color = "#fd0d0d" # Bootstrap primary color and theme color for Safari and Windows
color_scheme = "auto" # Must be "auto", "dark", or "light"
date_format = ":date_long" # Hugo date format
external_link_new_tab = false # Open external links in new tabs
file_edit_url = "" # Example: "https://github.com/eristocrates/neocities/tree/main/content/%s"
file_history_url = "" # Example: "https://github.com/eristocrates/neocities/commits/main/content/%s"
keyword_style = "text" # Must be "text" or "pills"
math = false # Enable math typesetting
menu_style = "underline" # Must be "links", "pills", "tabs", or "underline"
site_description = "content for the most attractive and distinguished of eristocrats. But you can read too!"
site_title = "the eristocracy"
style = "" # CSS included at the end of the stylesheet, before style-last.css

[[params.paige.feed.atom.authors]]
email = "eristocrates@gmail.com"
name = "eristocrates"
url = "eristocrates.dev"

[params.paige.feed.rss]
managing_editor = "eristocrates@gmail.com"
web_master = "eristocrates@gmail.com"

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[permalinks]
